---

platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY:
  TAG: latest
  CONTEXT:

inputs:
- name: concourse-http-api-resource

outputs:
- name: image

caches:
- path: cache

run: {path: build}
